- README.md
**Initialize the project**
Have two current directories to keep things separated
1) web - isolated environment to focus on the website development
2) embedded - isolated environment to focus on embedded development with the physical devices
> initialize project template

- project/web/app/globals.css
- project/web/app/layout.tsx
- project/web/app/page.tsx
- project/web/app/predictive-analysis/page.tsx
Pull request to track incremental changes.
> Add Homepage

- project/embedded/src/wearable/heart_rate.cpp
- project/embedded/src/wearable/heart_rate.h
- project/embedded/src/wearable/wearable.ino
Initialize code for wearable. There is one `.ino` file for the arduino project and `.h.` and `.cpp.` for helper files
> initialize code for wearable

- project/web/backend/server.js
* The change is to setup an endpoint to forward data coming from outside source (in this case, the wearable) to store into database. 
1) Run `node server.js` in `/web/backend/server.js` path
2) Use a service such as `postman` for simulating requests sent to backend endpoint
* The format of the request body is :
```
{
"wearable_id"   : <serial>,
"timestamp"     : <timestamp with time zone>, // this will be NULL b/c we will have request handle inserting the time into db
"battery_level" : <double precision>,
"heart_rate"    : <double precision>,
"blood_oxygen"  : <double precision>,
"longitude"     : <double precision>,
"latitude"      : <double precision>,
"num_falls"     : <integer>,
"num_steps"     : <integer>
}
```
* The example is shown below using postman
3) The result in the database …
> Added endpoint for inserting wearable data to db

- project/web/app/biometric-monitor/layout.css
- project/web/app/biometric-monitor/page.tsx
Added in the darkening overlay for the page with the remove component on top. Easy to change if needed in the css.
> Darkening effect for remove patient button

- project/web/app/(main)/biometric-monitor/page.tsx
- project/web/app/(main)/layout.css
- project/web/app/(main)/layout.tsx
- project/web/backend/server.js
1. Removed unnecessary error logging from biometric-monitor/page.tsx and backend/server.js.
2. Fixed indentation in layout.css.
3. Added styling to sidebar to set font-size to 16px for, and remove underlines from navigation links for consistency.
4. Added fetch POST request to layout.tsx.
5. Added layout endpoint to backend/server.js.
> Add Layout Endpoint

- project/web/app/(main)/biometric-monitor/BloodOxygenChart.tsx
- project/web/app/(main)/biometric-monitor/HeartRateChart.tsx
- project/web/app/(main)/biometric-monitor/NotificationChart.css
- project/web/app/(main)/biometric-monitor/NotificationChart.tsx
- project/web/app/(main)/biometric-monitor/PatientComponent.css
- project/web/app/(main)/biometric-monitor/PatientComponent.tsx
- project/web/app/(main)/biometric-monitor/homepage.css
- project/web/app/(main)/biometric-monitor/page.tsx
Summary of changes: 
1. Adjusted homepage to be responsive and to switch to flex-direction:column on smaller screens 
Before : ![Screenshot 2025-04-19 at 4 10 27 pm](https://github.com/user-attachments/assets/3e6eb3a9-7b4e-4fc5-85e6-f2ba11ed4694)
After ![Screenshot 2025-04-19 at 4 10 45 pm](https://github.com/user-attachments/assets/b23148e2-48c5-4166-bef3-cd43462ee5a8)
2. Modularised the homepage.css file into multiple different files based off on the components for easier readability.
> Home page css fixes

- project/web/app/(main)/biometric-monitor/HeartRateChart.tsx
- project/web/app/(main)/biometric-monitor/page.tsx
- project/web/backend/server.js
Website will update the heart rate levels of a patient every 5 seconds right now.
Right now the query for getting the heartrate levels has a hardcoded patient_id. To test it out, make sure to login in with a caretaker that has a patient that has wearable data. Change the hardcoded patient_id value to the one in your database that is linked to the caretaker.
> HeartRate endpoint

- project/web/app/(main)/biometric-monitor/HeartRateChart.tsx
- project/web/app/(main)/biometric-monitor/StepCounterChart.tsx
- project/web/app/(main)/biometric-monitor/homepage.css
- project/web/app/(main)/biometric-monitor/page.tsx
- project/web/app/(main)/biometric-monitor/stepCounter.css
- project/web/app/(main)/components/patient-component/PatientComponent.css
- project/web/app/(main)/components/patient-component/PatientComponent.tsx
- project/web/app/(main)/predictive-analysis/patientComponent.tsx
Implemented Step counting component
Also fixed the patient components for the add and remove buttons.
> Step counts

- project/web/app/(main)/biometric-monitor/page.tsx
- project/web/app/(main)/components/patient-component/PatientComponent.css
- project/web/app/(main)/components/patient-component/PatientComponent.tsx
- project/web/backend/server.js
1. Added GET request in frontend to retrieve Patient data to be displayed in Select Patient dropdown component.
2. Added POST request in frontend to send user input fields for Patient attributes to backend.
3. Added "patients" endpoint to handle GET/POST requests to facilitate retrieve/insert functionalities.
4. Added error checking to Add Patient form, and CSS tweaks for spacing.
> Implement Add Patient Endpoint.

- project/web/app/(main)/battery-tracker/barChart.tsx
- project/web/app/(main)/battery-tracker/battery-tracker.css
- project/web/app/(main)/battery-tracker/batteryGauge.tsx
- project/web/app/(main)/battery-tracker/page.tsx
lemme know if the responsiveness of both bar chart and gauge chart should be more proportional or no
> gauge chart responsiveness, resolve overwriting homepage

- project/web/app/(main)/components/patient-component/PatientComponent.css
- project/web/app/(main)/components/patient-component/PatientComponent.tsx
- project/web/backend/server.js
1. Changed PatientComponent.tsx API calls to work for both local/AWS EC2 instances.
2. Modified Patient component to display current Gender, Age, Height, and Weight of chosen patient.
3. Added error-checking for patient age.
4. Added Save Changes button.
5. Added endpoint for updating Gender, Age, Height, and Weight of chosen patient.
6. Added JWT middleware.
7. Added PATCH fetch request to PatientComponent.tsx.
8. Replace Age and Weight dropdowns with text fields.
> Patient Component Improvements

- project/web/app/(main)/components/patient-component/PatientComponent.css
- project/web/app/(main)/components/patient-component/PatientComponent.tsx
- project/web/backend/server.js
1. Edit Select dropdown to be Select Patient.
2. Add fetch request to PatientComponent.tsx.
3. Add DELETE endpoint to server.js.
> Add Delete Patient Functionality

- project/web/app/(main)/components/patient-component/PatientComponent.css
- project/web/app/(main)/components/patient-component/patient-dropdown-location.tsx
- project/web/app/(main)/components/patient-component/patient-dropdown.css
- project/web/app/(main)/location/location.css
- project/web/app/(main)/location/page.tsx
Added the dropdown menu for the location tracker page
> Location tracker patient component

- project/web/app/(main)/biometric-monitor/HeartRateChart.tsx
- project/web/app/(main)/components/patient-component/PatientComponent.tsx
- project/web/app/(main)/context/Wearable-context.tsx
- project/web/app/(main)/context/WearableContext.tsx
- project/web/app/(main)/layout.tsx
- project/web/backend/server.js
When selecting a patient, you will see heartrate of the patient, it will fetch for any new data every 3 seconds. I also fixed an issue when you have 2 patients with the same name, now it will fetch correctly if this happens.
> Wearable_id context api / for data retrieval for heartrate depending on patient selected 

- project/embedded/src/wearable/BAT_driver.cpp
- project/embedded/src/wearable/BAT_driver.h
- project/embedded/src/wearable/wearable.ino
1. added battery level to device
> added battery level

- project/embedded/src/wearable/RTC_PCF85063.cpp
- project/embedded/src/wearable/RTC_PCF85063.h
- project/embedded/src/wearable/wearable.ino
> added time

- project/web/app/(main)/battery-tracker/page.tsx
- project/web/app/(main)/biometric-monitor/HeartRateChart.tsx
- project/web/app/(main)/predictive-analysis/page.tsx
1. Fixed import names to some modules
> fix imports

- project/embedded/src/wearable/RTC_PCF85063.cpp
- project/embedded/src/wearable/fall_detection.cpp
- project/embedded/src/wearable/fall_detection.h
- project/embedded/src/wearable/step_detection.cpp
- project/embedded/src/wearable/step_detection.h
- project/embedded/src/wearable/wearable.ino
1. refactored files and timestamp
> refactored files

- project/web/app/(main)/biometric-monitor/page.css
Fixed text padding to the left when navigating from the home page -> predictive analysis page
> fixed h1 css property overriding on the preditive-analysis charts

- project/web/app/(main)/layout.tsx
- project/web/app/AuthGuard.tsx
- project/web/app/layout.tsx
Added an authguard component which returns a loading page when the user isn't logged in instead of briefly showing our page contents
> Authguard implementation for redirection 

- project/web/app/(main)/components/patient-component/PatientComponent.tsx
- project/web/backend/server.js
- project/web/package-lock.json
- project/web/package.json
1 . Installed multer depedency to support uploading images 
2. added a new row in the patients database to hold the image url of the profile picture
3. added the ability to upload your own profile image
> Upload profile image
